# Generated by Django 3.1.5 on 2021-01-09 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_photo_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 9, 17, 26, 55, 780527)),
        ),
    ]
