# Generated by Django 3.1.5 on 2021-01-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210109_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default=None, upload_to='avatars/'),
        ),
    ]
